steps:
  - name: gcr.io/cloud-builders/docker:18.09.0
    args:
      - image
      - build
      - --pull
      - -t
      - gcr.io/$PROJECT_ID/cloud-builders/gcloud-make:latest
      - .

images:
  - gcr.io/$PROJECT_ID/cloud-builders/gcloud-make:latest

timeout: 600s
