steps:
  - name: gcr.io/cloud-builders/docker:18.09.0
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/cloud-builders/docker:18.09.2
      - .
  - name: gcr.io/cloud-builders/docker:18.09.0
    args:
      - tag
      - gcr.io/$PROJECT_ID/cloud-builders/docker:18.09.2
      - gcr.io/$PROJECT_ID/cloud-builders/docker:latest

images:
  - gcr.io/$PROJECT_ID/cloud-builders/docker:18.09.2
  - gcr.io/$PROJECT_ID/cloud-builders/docker:latest
