steps:
  - name: gcr.io/cloud-builders/docker:18.09.0
    args:
      - image
      - build
      - --pull
      - -t
      - gcr.io/$PROJECT_ID/cloud-builders/httrack:$_TAG
      - .
  - name: gcr.io/cloud-builders/docker:18.09.0
    args:
    - image
    - tag
    - gcr.io/$PROJECT_ID/cloud-builders/httrack:$_TAG
    - gcr.io/$PROJECT_ID/cloud-builders/httrack:latest

images:
  - gcr.io/$PROJECT_ID/cloud-builders/httrack:$_TAG
  - gcr.io/$PROJECT_ID/cloud-builders/httrack:latest

timeout: 600s
